#!/usr/bin/env bash

if ! hash secret-tool 2>/dev/null; then
  exit 0
fi

declare command="$1"

shift 1

case "$command" in
  getopts)
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --no-cache)
          echo ENVY_LIBSECRET_NOCACHE=1
          echo 1 >&3

          shift
        ;;

        *) echo 0 >&3 ; shift ;;
      esac
    done
  ;;

  help)
    printf "envy-libsecret: cache values using libsecret"
    printf "--------------------------------------------"
    printf "%s\\t%s\\n" "--no-cache" "disable caching"
  ;;

  read)
    if [[ $ENVY_LIBSECRET_NOCACHE != "1" ]]; then
      secret-tool lookup "envy-libsecret" "$ENVY_PROFILE/$ENVY_VAR"
    fi
  ;;

  write)
    if [[ $ENVY_LIBSECRET_NOCACHE != "1" ]]; then
      echo -n "$ENVY_VALUE" | \
        secret-tool store -l "envy-libsecret/$ENVY_PROFILE/$ENVY_VAR" \
        envy-libsecret "$ENVY_PROFILE/$ENVY_VAR"
    fi
  ;;
esac
